export 'package:cine_app/presentation/widgets/shared/custom_bottom_navigationbar.dart'; 
export 'package:cine_app/presentation/widgets/shared/fullscreen_loader.dart'; 
export 'package:cine_app/presentation/widgets/movie_horizontal_listview.dart'; 
export 'package:cine_app/presentation/widgets/movies_gridview.dart';
export 'package:cine_app/presentation/widgets/movies_slideshow.dart';
export "package:cine_app/presentation/widgets/shared/custom_appbar.dart";
export 'package:cine_app/presentation/widgets/shared/movie_poster.dart';
export 'package:cine_app/presentation/widgets/shared/title_subtitle.dart';
export 'package:cine_app/presentation/widgets/shared/poster_loading_progress.dart';