name: cine_app
description: This application shows information about movies, and actors from
  the API provided by https://www.themoviedb.org
publish_to: 'eserdeiro'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  card_swiper: ^3.0.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.7
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.4.7
  go_router: ^12.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  path_provider: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/assets/icon/icon.png"

flutter_native_splash:
  color: "#1f1d2b"
  android_12:
    color: "#1f1d2b"

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/images/
    - lib/assets/icon/

  fonts:
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
