 //Generated by https://app.quicktype.io/ 
 //https://api.themoviedb.org/3/movie/now_playing?api_key=API_KEY&language=es-ARG

 //Here it shows the page data

import 'package:cine_app/infrastructure/models/index.dart';

class MovieDbResponse {

    final int page;
    final List<ItemFromMovieDbResponse> results;
    final int totalPages;
    final int totalResults;

    MovieDbResponse({
        required this.page,
        required this.results,
        required this.totalPages,
        required this.totalResults,
    });

    factory MovieDbResponse.fromJson(Map<String, dynamic> json) => MovieDbResponse(
        page: json['page'],
        results: List<ItemFromMovieDbResponse>.from(json['results'].map((x) => ItemFromMovieDbResponse.fromJson(x))),
        totalPages: json['total_pages'],
        totalResults: json['total_results'],
    );

    Map<String, dynamic> toJson() => {
        'page': page,
        'results': List<dynamic>.from(results.map((x) => x.toJson())),
        'total_pages': totalPages,
        'total_results': totalResults,
    };
}
 
